# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/root/"
  config.vm.synced_folder ".", "/root/", type: "rsync"
  config.vm.provision "shell", inline: "/root/test.sh"
end
